build_and_test_web_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter build web --release --base-href /sushiro-calculator/
  artifacts:
    paths:
      - build/web

pages:
  stage: deploy
  script:
    - cp -r build/web public
  artifacts:
    paths:
      - public
